### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by client9** [docker/go-healthcheck#1]
hi guys...

Looks good!

Could you do me a kindness and add a `LICENSE` file.  It will save me a trip to the lawyers.

Thanks!

nickg

**Comment by stevvooe** [comment]
This is Apache2. We'll get the project template applied.

@thaJeztah Let's get this project into proper shape.

**Comment by thaJeztah** [comment]
Yup, let me get that fixed. Wasn't aware of this project :smile:
